version: "2.4"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    sysctls:
      - net.core.somaxconn=65536
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - public
      - common
    restart: "always"
    logging:
      options:
        max-size: 100m
        max-file: "5"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:rw
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    restart: "always"

  api:
    build:
      context: ../../.
      args:
        - PROD=0
    container_name: api_endpoint
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - NODE_HOST=0.0.0.0
      - NODE_PORT=3000
      - NODE_LOG=on
      - GOOGLE_CLIENT_ID=783060610997-msflf7mb73krpk3vt8dvsdv5952k5c89.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=Equ0PBlzYkTKwtvHiX0RIu6l
      - GOOGLE_MAPS_KEY=AIzaSyCaLa_8AolnOa5IJ4egRF4-a55IUulCF70
      - FACEBOOK_CLIENT_ID=1217577778573857
      - FACEBOOK_CLIENT_SECRET=6e1fd784b90c3154d31649d1953e236e
      - DATABASE=mongodb://mongo:27017/test
      - JWT_SECRET=test
      - SENTRY_DSN=https://274d41997d554fd8b20317bd345ae6b1@sentry.alphax-ds.de/27
      - VERIFY_EMAIL_TEMPLATE=10079139
      - VERIFY_EMAIL_ACTION_URL=https://api.dev.tailor-directory.com/one-time-pass/confirm-email
      - VERIFY_USER_EMAIL_ACTION_URL=https://api.dev.tailor-directory.com/one-time-pass/me/confirm-email
      - FORGOT_PASSWORD_TEMPLATE=9921763
      - VIRTUAL_HOST=api.dev.tailor-directory.com
      - LETSENCRYPT_HOST=api.dev.tailor-directory.com
      - LETSENCRYPT_EMAIL=oleg.or@room4.team
      - VIRTUAL_PORT=3000
      - S3_ACCESS_KEY=AKIAXUFWHMX5LDCWXXHI
      - S3_SECRET_KEY=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
      - S3_REGION=us-east-1
      - S3_BUCKET_NAME=tailor-directory-dev
      - EMAIL_KEY=8de8aab1-25ff-4b22-be3f-49fdaea56a5c
      - EMAIL_ENABLE=true
      - EMAIL_FROM=mail@tailor-directory.com
      - FORGOT_PASSWORD_ACTION_URL=https://api.dev.tailor-directory.com/auth/forgot-password
    ports:
      - 3000:3000
    volumes:
      - "../../volumes/profiling_api:/var/www/app/profiling"
      - "../../src:/var/www/app/src"
    depends_on:
      - mongo
    networks:
      - public
    restart: always
    logging:
      options:
        max-size: 100m
        max-file: "5"

  mongo:
    image: mongo:4.0.4
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - public
    restart: always
    logging:
      options:
        max-size: 100m
        max-file: "5"

volumes:
  mongo:
    driver: local
  api:
    driver: local
  nginx-certs:
    driver: local
  nginx-vhost:
    driver: local
  nginx-html:
    driver: local

networks:
  common:
    external:
      name: common
  public:
    driver: bridge